# Generated by Django 3.2.4 on 2021-06-23 12:17

import dirtyfields.dirtyfields
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('cannot_change_me', models.BooleanField(default=False)),
                ('can_change_me', models.BooleanField(default=False)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
