# Generated by Django 3.2.6 on 2021-08-18 11:05

import dirtyfields.dirtyfields
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('cannot_change_me', models.BooleanField(default=False)),
                ('can_change_me', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
