# Generated by Django 3.2.6 on 2021-08-20 15:32

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_fakemodel2_another_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change_me', models.BooleanField(default=False)),
                ('cannot_change_me', models.BooleanField(default=False)),
                ('fake_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytest.fakemodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubSubFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change_me', models.BooleanField(default=False)),
                ('cannot_change_me', models.BooleanField(default=False)),
                ('sub_fake_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytest.subfakemodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
