version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run isort
          command: |
            poetry run isort .
      - run:
          name: Run black
          command: |
            poetry run black .
#      - run:
#          name: Run flake8
#          command:
#            poetry run flake8 .
      - run:
          name: Run Pytest
          command: |
            poetry run pytest

  deployment:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry config pypi-token.pypi "${POETRY_PYPI_TOKEN}"
            poetry publish --build --no-interaction
workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test

  deployment-workflow:
    jobs:
      # Runs build and test, but now just on Git tags (created from a GitHub release)
      - build-and-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      # Runs the deployment job, only on the Git tags
      - deployment:
          requires:
            - build-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
