name: Continues Integration

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]
env:
  PYTHON_VERSION: 3.9
jobs:
  run-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Run isort
        run: |
          poetry run isort . --check
      - name: Run black
        run: |
          poetry run black --check --diff .
      - name: Run flake8
        run: |
          poetry run flake8 .
      - name: Run pytest
        run: |
          poetry run pytest --cov=django_fsm_freeze
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}

  deploy:
    name: Build and Publish on release
    # Only publish the package when a release is published
    if: github.event.action == 'published'
    needs:
      - run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          poetry --version
      - name: Build and Push to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.POETRY_CI_TOKEN }}
          poetry publish --build --no-interaction
