name: Continues Integration

on:
  push:
    branches:
      - main
  pull_request:
env:
  PYTHON_VERSION: 3.9
jobs:
  run-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Run isort
        run: |
          poetry run isort . --check
      - name: Run black
        run: |
          poetry run black --check --diff .
      - name: Run flake8
        run: |
          poetry run flake8 .
      - name: Run pytest
        run: |
          poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          fail_ci_if_error: true
