name: Publish to PyPI
on:
  # Only publish the package when a release is published
  release:
    types: [published]
env:
  PYTHON_VERSION: 3.9
jobs:
  deploy:
    name: Build and Publish on release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          poetry --version
      - name: Build and Push to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.POETRY_CI_TOKEN }}
          poetry publish --build --no-interaction
