name: Send Coverage Result

# access to secrets
# only if the workflow has completed successfully
on:
  workflow_run:
    workflows: ["Continues Integration"]
    types: [completed]
env:
  PYTHON_VERSION: 3.9
jobs:
  send-coveralls:
    name: Send coverage result to coveralls
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Send coverage
        run: |
          poetry run coveralls
